// Generated by https://quicktype.io

export interface User {
  id: number
  name: string
  username: string
  email: string
}

export interface Post {
  id: number
  userId: number
  title: string
  body: string
  actions?: JSX.Element
}

export interface PostColumn {
  id: 'id' | 'userId' | 'title' | 'body' | 'actions'
  label: string
  minWidth?: number
  align?: 'right'
  format?: (value: any) => React.ReactNode
}

export interface PostFilter {
  title?: string | null
  authorId?: number | null
}
